blueprint:
  name: ZBMINIR2 Double-Click
  description: Toggles light on double click without turn off the switch of ZBMINIR2. Detached Relay has to be enabled
  domain: automation
  author: Christian Herkenhoff
  input:
    zbminir2_device:
      name: ZBMINIR2 device
      description: ZBMINIR2 device, ensure to activate "Detach relay mode"
      selector:
        device:
          filter:
            - manufacturer: SONOFF
              model: Zigbee smart switch
          multiple: false
    target:
      name: Toggle target lights or switches
      description: Double click will toggle the lights or switches
      selector:
        entity:
          filter:
            - domain:
                - light
                - switch
          multiple: true

# Allow multiple executions in parallel, up to 2 at the same time
mode: parallel
max: 2

# Trigger on MQTT device button press
triggers:
  - domain: mqtt
    device_id: !input zbminir2_device
    type: action
    subtype: toggle
    trigger: device

condition: []

action:
  # Check if this is the first active instance
  - if:
      - condition: template
        alias: Second execution of automation
        value_template: "{{ this.attributes.current == 1 }}"
    then:
      # Toggle the light only if this is the second execution
      # Only toggle if list is not empty
      - action: homeassistant.toggle
        target:
          entity_id: !input target
    else:
      # On first execution, wait 2 seconds
      - delay:
          seconds: 2
